---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
  labels:
    operators.coreos.com/opentelemetry-product.openshift-opentelemetry-operator: ""
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  {{- with .Values.telemetry }}
  channel: {{ .channel | default "Stable" }}
  {{- end }}
  installPlanApproval: Automatic
  name: opentelemetry-product
  source: {{ $.Values.catalogSource | default "redhat-operators" }}
  sourceNamespace: openshift-marketplace
  startingCSV: opentelemetry-operator.v0.135.0-1
