---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.observability.channel | default "latest" }}
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: {{ $.Values.catalogSource | default "redhat-operators" }}
  sourceNamespace: openshift-marketplace
