---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    deviceClasses:
{{- range .Values.localStorage.nodes }}
    - name: vg1
      fstype: xfs
      nodeSelector:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - {{ .name }}
      deviceSelector: 
{{ toYaml .deviceSelector | nindent 8 }}
        forceWipeDevicesAndDestroyAllData: {{ .forceWipeDrives | default false }}
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90 
        overprovisionRatio: 10
        chunkSize: 128Ki 
        chunkSizeCalculationPolicy: Static
{{- end }}