---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    deviceClasses:
    - name: vg1
      fstype: xfs
      default: true
      nodeSelector:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
{{- range .Values.localStorage.nodes }}
                  - {{ . }}
{{- end }}
      deviceSelector:
        paths:
{{- range .Values.localStorage.deviceSelectorPaths }}
          - {{ . }}
{{- end }}
        forceWipeDevicesAndDestroyAllData: {{  .Values.localStorage.forceWipeDrives | default false }}
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90 
        overprovisionRatio: 10
        chunkSize: 128Ki 
        chunkSizeCalculationPolicy: Static