{{ if .Values.convergedStorage }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: converged-storage
  namespace: {{ .Values.targetNamespace | default "openshift-gitops" }}
  labels:
    application: converged-storage
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/acp-standard-services-public.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/converged-storage
    helm:
      values: |
        convergedStorage:
{{- toYaml .Values.convergedStorage | nindent 10 }}
{{ end }}