{{- with .Values.pipelines }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.namePrefix | default "" }}pipelines
  namespace: openshift-gitops
  labels:
    application: pipelines
spec:
  destination:
    {{- if $.Values.destination }}
    name: {{ $.Values.destination }}
    {{- else }}
    name: ''
    server: https://kubernetes.default.svc
    {{- end }}
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: {{ $.Values.gitRepoURL | default "https://github.com/RedHatEdge/acp-standard-services-public.git" }}
    targetRevision: {{ $.Values.gitBranch | default "main" }}
    path: charts/pipelines
    helm:
      values: |
        pipelines:
{{- toYaml . | nindent 10 }}
{{- end }}
