{{ if .Values.virtualization }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualization
  namespace: {{ .Values.targetNamespace | default "openshift-gitops" }}
  labels:
    application: virtualization
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/acp-standard-services-public.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/virtualization
    helm:
      values: |
        virtualization:
{{- toYaml .Values.virtualization | nindent 10 }}
{{ end }}
