{{- with .Values.certificateManagement }}
{{ if .issueAPICert }}
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.{{ .clusterBaseDNSZone }}
        servingCertificate:
          name: openshift-api-cert
{{ end }}
{{- end }}
