{{- with .Values.certificateManagement }}
{{ if .issueIngressCert }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  defaultCertificate:
    name: router-cert
{{ end }}
{{- end }}