{{- range .Values.certificateManagement.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
{{- toYaml .stringData | nindent 2 }}
{{- end }}