---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  featureGates:
{{- with .Values.virtualization }}
    enableCommonBootImageImport: '{{ .commonBootImageImport | default true }}'
    nonRoot: '{{ .nonRoot | default true }}'
    withHostPassthroughCPU: '{{ .hostCPUPassThrough | default true }}'
{{- end }}