{{- range .Values.virtualization.vlanNetworkAttachmentDefinitions }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan{{ .vlan }}
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/{{ .bridgeInterface }}
    argocd.argoproj.io/sync-wave: "1"
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "vlan{{ .vlan }}", 
    "type": "cnv-bridge", 
    "bridge": "{{ .bridgeInterface }}", 
    "macspoofchk": true
  }'
{{- end }}