{{- $versionParts := .Values.convergedStorage.version | toString | splitList "." }}
{{- $minorVersion := 0 }}
{{- if gt (len $versionParts) 1 }}
{{- $minorVersion = index $versionParts 1 | int }}
{{- end }}
{{- if lt $minorVersion 19 }}
---
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
{{- end }}