---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-disks
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{- with .Values.localStorageForConvergedStorage }}
  storageClassName: {{ .storageClassName }}
  volumeMode: {{ .volumeMode }}
  deviceInclusionSpec:
{{- toYaml .deviceInclusionSpec | nindent 4 }}
{{- end }}
